In [1]:
import json
import pandas as pd

In [2]:
# dataset home page: https://brasil.io/dataset/covid19/caso
# csv listed at: https://data.brasil.io/dataset/covid19/_meta/list.html
data = pd.read_csv("https://data.brasil.io/dataset/covid19/caso_full.csv.gz")

# 1. Inspect the data

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11193 entries, 0 to 11192
Data columns (total 15 columns):
city                                             11193 non-null object
city_ibge_code                                   10906 non-null float64
date                                             11193 non-null object
estimated_population_2019                        10906 non-null float64
is_repeated                                      11193 non-null bool
is_last                                          11193 non-null bool
last_available_confirmed                         11193 non-null int64
last_available_confirmed_per_100k_inhabitants    10761 non-null float64
last_available_date                              11193 non-null object
last_available_death_rate                        1702 non-null float64
last_available_deaths                            10783 non-null float64
place_type                                       11193 non-null object
state                                            11193 non-null object
new_confirmed                                    11193 non-null int64
new_deaths                                       11193 non-null int64
dtypes: bool(2), float64(5), int64(3), object(5)
memory usage: 1.1+ MB

In [4]:
data['new_confirmed'].sum(), data['new_deaths'].sum()

(19592, 1045)

In [5]:
data.groupby(['place_type']).size()

place_type
city    11193
dtype: int64

In [6]:
data.groupby(['is_repeated']).size()

is_repeated
False    9787
True     1406
dtype: int64

In [7]:
data.loc[0:1, ["date", "city", "place_type", "is_repeated", "last_available_date", 
               "last_available_confirmed", "last_available_deaths", "new_confirmed", "new_deaths"]]

,date,city,place_type,is_repeated,last_available_date,last_available_confirmed,last_available_deaths,new_confirmed,new_deaths
0,2020-02-25,São Paulo,city,False,2020-02-25,1,NaN,0,0
1,2020-02-26,São Paulo,city,True,2020-02-25,1,NaN,0,0

In [8]:
print(data.head(2))

        city  city_ibge_code        date  estimated_population_2019  \
0  São Paulo       3550308.0  2020-02-25                 12252023.0
1  São Paulo       3550308.0  2020-02-26                 12252023.0

   is_repeated  is_last  last_available_confirmed  \
0        False    False                         1
1         True    False                         1

   last_available_confirmed_per_100k_inhabitants last_available_date  \
0                                        0.00816          2020-02-25
1                                        0.00816          2020-02-25

   last_available_death_rate  last_available_deaths place_type state  \
0                        NaN                    NaN       city    SP
1                        NaN                    NaN       city    SP

   new_confirmed  new_deaths
0              0           0
1              0           0

In [9]:
data.groupby(["date"])["new_confirmed", "new_deaths"].sum()

            new_confirmed  new_deaths
date
2020-02-25              0           0
2020-02-26              0           0
2020-02-27              0           0
2020-02-28              1           0
2020-02-29              0           0
2020-03-01              0           0
2020-03-02              0           0
2020-03-03              0           0
2020-03-04              1           0
2020-03-05              4           0
2020-03-06              2           0
2020-03-07              9           0
2020-03-08              6           0
2020-03-09              0           0
2020-03-10              4           0
2020-03-11             14           0
2020-03-12             45           0
2020-03-13              6           0
2020-03-14             38           0
2020-03-15             19           0
2020-03-16            121           0
2020-03-17             47           1
2020-03-18            187          -1
2020-03-19            125           7
2020-03-20            237           4
2020-03-21            211           1
2020-03-22            192           0
2020-03-23            274           1
2020-03-24            238           3
2020-03-25            780          43
2020-03-26            426          18
2020-03-27            488          16
2020-03-28            250           5
2020-03-29            305           8
2020-03-30            629          60
2020-03-31           1164          36
2020-04-01           1107          42
2020-04-02           1168          40
2020-04-03           1113          81
2020-04-04           1131          78
2020-04-05           1082          53
2020-04-06            838          74
2020-04-07           1821         121
2020-04-08           1968         118
2020-04-09           1870         133
2020-04-10           1619         103
2020-04-11             52           0

In [10]:
data[data["state"] == "CE"].groupby(["date"])["new_deaths", "last_available_deaths", "new_confirmed", 
                                              "last_available_confirmed"].sum()

,new_deaths,last_available_deaths,new_confirmed,last_available_confirmed
date,,,,
2020-03-16,0,0.0,9,9
2020-03-17,0,0.0,1,10
2020-03-18,0,0.0,9,19
2020-03-19,0,0.0,1,20
2020-03-20,0,0.0,48,68
2020-03-21,0,0.0,16,84
2020-03-22,0,0.0,41,125
2020-03-23,0,0.0,39,164
2020-03-24,0,0.0,21,185
2020-03-25,0,0.0,26,211
2020-03-26,3,3.0,26,237
2020-03-27,0,3.0,45,282
2020-03-28,1,4.0,40,322
2020-03-29,1,5.0,37,359
2020-03-30,0,5.0,23,382
2020-03-31,2,7.0,19,401
2020-04-01,2,9.0,44,445
2020-04-02,-9,0.0,119,564
2020-04-03,22,22.0,94,658
2020-04-04,1,23.0,88,746
2020-04-05,12,35.0,218,964
2020-04-06,1,36.0,83,1047
2020-04-07,4,40.0,143,1190
2020-04-08,0,40.0,0,1190
2020-04-09,0,40.0,0,1190
2020-04-10,0,40.0,0,1190
2020-04-11,0,40.0,0,1190

In [11]:
data.loc[(data["new_deaths"] < 0) | (data["new_confirmed"] < 0), 
         ["date", "city", "last_available_date", "last_available_confirmed", "last_available_deaths",  "new_confirmed", "new_deaths"]]

,date,city,last_available_date,last_available_confirmed,last_available_deaths,new_confirmed,new_deaths
288,2020-03-18,Jaboatão dos Guararapes,2020-03-18,1,NaN,-1,0
329,2020-03-18,São Paulo,2020-03-18,214,NaN,58,-1
414,2020-03-19,Santo André,2020-03-19,2,NaN,-4,0
417,2020-03-19,São Caetano do Sul,2020-03-19,1,NaN,-5,0
465,2020-03-20,Uberlândia,2020-03-20,1,0.0,-1,0
568,2020-03-21,Importados/Indefinidos,2020-03-21,0,0.0,-1,0
577,2020-03-21,Juiz de Fora,2020-03-21,4,0.0,-1,0
668,2020-03-21,Importados/Indefinidos,2020-03-21,0,0.0,-8,0
686,2020-03-22,Importados/Indefinidos,2020-03-22,0,NaN,-7,0
711,2020-03-22,Aparecida de Goiânia,2020-03-22,1,0.0,-1,0
755,2020-03-22,Umuarama,2020-03-22,0,0.0,-1,0
758,2020-03-22,Importados/Indefinidos,2020-03-22,2,0.0,-2,0
883,2020-03-23,Coronel Fabriciano,2020-03-23,1,0.0,-1,0
967,2020-03-23,Sapiranga,2020-03-23,1,0.0,-1,0
970,2020-03-23,Taquara,2020-03-23,1,0.0,-1,0
1073,2020-03-24,Importados/Indefinidos,2020-03-24,2,0.0,-26,0
1320,2020-03-25,Importados/Indefinidos,2020-03-25,4,0.0,-1,0
1333,2020-03-25,Importados/Indefinidos,2020-03-25,0,0.0,-2,0
1353,2020-03-25,Camaquã,2020-03-25,0,0.0,-1,0
1389,2020-03-25,Balneário Camboriú,2020-03-25,7,0.0,-2,0
1394,2020-03-25,Chapecó,2020-03-25,2,0.0,-1,0
1396,2020-03-25,Florianópolis,2020-03-25,16,0.0,-4,0
1412,2020-03-25,São José,2020-03-25,5,0.0,-1,0
1416,2020-03-25,Tubarão,2020-03-25,8,0.0,-1,0
1451,2020-03-25,Vargem Grande Paulista,2020-03-25,0,1.0,-1,1
1484,2020-03-26,Importados/Indefinidos,2020-03-26,0,0.0,-2,0
1502,2020-03-26,Importados/Indefinidos,2020-03-26,0,0.0,-3,0
1629,2020-03-26,Sapiranga,2020-03-26,1,0.0,-1,0
1655,2020-03-26,Laguna,2020-03-26,0,0.0,-1,0
1675,2020-03-26,Cotia,2020-03-26,5,0.0,-1,0
...,...,...,...,...,...,...,...
7523,2020-04-07,Siderópolis,2020-04-07,4,0.0,-1,0
7563,2020-04-07,Caieiras,2020-04-07,21,4.0,-1,0
7577,2020-04-07,Franca,2020-04-07,1,0.0,-1,0
7695,2020-04-08,São Gabriel da Cachoeira,2020-04-08,0,0.0,-1,0
7713,2020-04-08,Camaçari,2020-04-08,9,0.0,-1,0
7902,2020-04-08,Governador Valadares,2020-04-08,2,0.0,-1,0
7965,2020-04-08,Chapada dos Guimarães,2020-04-08,0,0.0,-1,0
8363,2020-04-08,Bauru,2020-04-08,8,1.0,1,-1
8429,2020-04-08,Mogi das Cruzes,2020-04-08,30,0.0,3,-1
8456,2020-04-08,Santa Cruz do Rio Pardo,2020-04-08,1,0.0,-1,0
8457,2020-04-08,Santa Isabel,2020-04-08,1,0.0,-1,0
8497,2020-04-09,Importados/Indefinidos,2020-04-09,6,0.0,0,-1
8552,2020-04-09,Ipiaú,2020-04-09,12,0.0,6,-1
8692,2020-04-09,Icatu,2020-04-09,0,0.0,-1,0
8709,2020-04-09,Boa Esperança,2020-04-09,2,0.0,-1,0
8929,2020-04-09,Paranaguá,2020-04-09,5,2.0,-1,1
9174,2020-04-09,Paulo Lopes,2020-04-09,1,0.0,-1,0
9305,2020-04-09,Pariquera-Açu,2020-04-09,1,0.0,-1,0
9550,2020-04-10,Importados/Indefinidos,2020-04-10,3,0.0,-1,0
9614,2020-04-10,Importados/Indefinidos,2020-04-10,16,0.0,-2,0
9718,2020-04-10,Bayeux,2020-04-10,0,NaN,-1,0
9796,2020-04-10,Fazenda Rio Grande,2020-04-10,5,0.0,-1,0
9808,2020-04-10,Lapa,2020-04-10,2,0.0,-1,0
9869,2020-04-10,Itaguaí,2020-04-10,4,0.0,-2,0
9920,2020-04-10,Importados/Indefinidos,2020-04-10,7,NaN,-2,0
9979,2020-04-10,Gravataí,2020-04-10,13,0.0,-1,0
10054,2020-04-10,Importados/Indefinidos,2020-04-10,8,0.0,-3,0
10073,2020-04-10,Palhoça,2020-04-10,6,1.0,-1,0
10166,2020-04-10,Importados/Indefinidos,2020-04-10,93,0.0,3,-1
10530,2020-04-11,Ipatinga,2020-04-11,4,0.0,-1,0

# 2. Fix manually

# 3. Create `.json` with summarized data

In [12]:
data.rename(columns={"last_available_deaths": "deaths", "last_available_confirmed": "confirmed"}, inplace=True)

In [13]:
data_summary = data.groupby(['state', 'date'])['deaths', 'confirmed'].sum().reset_index()

data_summary["deaths"] = data_summary["deaths"].astype(int)
data_summary["confirmed"] = data_summary["confirmed"].astype(int)

In [14]:
data_summary.set_index("date", inplace=True)

In [15]:
data_summary.head(3)

           state  deaths  confirmed
date
2020-03-17    AC       0          3
2020-03-18    AC       0          3
2020-03-19    AC       0          4

In [16]:
data_summary.tail(10)

           state  deaths  confirmed
date
2020-04-02    TO       0         12
2020-04-03    TO       0         13
2020-04-04    TO       0         16
2020-04-05    TO       0         17
2020-04-06    TO       0         19
2020-04-07    TO       0         19
2020-04-08    TO       0         23
2020-04-09    TO       0         23
2020-04-10    TO       0         23
2020-04-11    TO       0         23

In [17]:
data_summary.loc[data_summary["state"] == "CE", "confirmed"].values

array([   9,   10,   19,   20,   68,   84,  125,  164,  185,  211,  237,
        282,  322,  359,  382,  401,  445,  564,  658,  746,  964, 1047,
       1190, 1190, 1190, 1190, 1190])

In [18]:
data_summary.loc[data_summary["state"] == "CE", "confirmed"].index

Index(['2020-03-16', '2020-03-17', '2020-03-18', '2020-03-19', '2020-03-20',
       '2020-03-21', '2020-03-22', '2020-03-23', '2020-03-24', '2020-03-25',
       '2020-03-26', '2020-03-27', '2020-03-28', '2020-03-29', '2020-03-30',
       '2020-03-31', '2020-04-01', '2020-04-02', '2020-04-03', '2020-04-04',
       '2020-04-05', '2020-04-06', '2020-04-07', '2020-04-08', '2020-04-09',
       '2020-04-10', '2020-04-11'],
      dtype='object', name='date')

In [19]:
data_summary.loc[data_summary["state"] == "CE", "deaths"].index

Index(['2020-03-16', '2020-03-17', '2020-03-18', '2020-03-19', '2020-03-20',
       '2020-03-21', '2020-03-22', '2020-03-23', '2020-03-24', '2020-03-25',
       '2020-03-26', '2020-03-27', '2020-03-28', '2020-03-29', '2020-03-30',
       '2020-03-31', '2020-04-01', '2020-04-02', '2020-04-03', '2020-04-04',
       '2020-04-05', '2020-04-06', '2020-04-07', '2020-04-08', '2020-04-09',
       '2020-04-10', '2020-04-11'],
      dtype='object', name='date')

In [20]:
output = [{"state_name": "Acre", "state_code": "AC", "region": "N", "confirmed":[], "deaths":[]},
          {"state_name": "Alagoas", "state_code": "AL", "region": "NE", "confirmed":[], "deaths":[]},
          {"state_name": "Amazonas", "state_code": "AM", "region": "N", "confirmed":[], "deaths":[]},
          {"state_name": "Amapá", "state_code": "AP", "region": "N", "confirmed":[], "deaths":[]},
          {"state_name": "Bahia", "state_code": "BA", "region": "NE", "confirmed":[], "deaths":[]},
          {"state_name": "Ceará", "state_code": "CE", "region": "NE", "confirmed":[], "deaths":[]},
          {"state_name": "Distrito Federal", "state_code": "DF", "region": "CO", "confirmed":[], "deaths":[]},
          {"state_name": "Espírito Santo", "state_code": "ES", "region": "SE", "confirmed":[], "deaths":[]},
          {"state_name": "Goiás", "state_code": "GO", "region": "CO", "confirmed":[], "deaths":[]},
          {"state_name": "Maranhão", "state_code": "MA", "region": "NE", "confirmed":[], "deaths":[]},
          {"state_name": "Minas Gerais", "state_code": "MG", "region": "SE", "confirmed":[], "deaths":[]},
          {"state_name": "Mato Grosso do Sul", "state_code": "MS", "region": "CO", "confirmed":[], "deaths":[]},
          {"state_name": "Mato Grosso", "state_code": "MT", "region": "CO", "confirmed":[], "deaths":[]},
          {"state_name": "Pará", "state_code": "PA", "region": "N", "confirmed":[], "deaths":[]},
          {"state_name": "Paraíba", "state_code": "PB", "region": "NE", "confirmed":[], "deaths":[]},
          {"state_name": "Pernambuco", "state_code": "PE", "region": "NE", "confirmed":[], "deaths":[]},
          {"state_name": "Piauí", "state_code": "PI", "region": "NE", "confirmed":[], "deaths":[]},
          {"state_name": "Paraná", "state_code": "PR", "region": "S", "confirmed":[], "deaths":[]},
          {"state_name": "Rio de Janeiro", "state_code": "RJ", "region": "SE", "confirmed":[], "deaths":[]},
          {"state_name": "Rio Grande do Norte", "state_code": "RN", "region": "NE", "confirmed":[], "deaths":[]},
          {"state_name": "Rondônia", "state_code": "RO", "region": "N", "confirmed":[], "deaths":[]},
          {"state_name": "Roraima", "state_code": "RR", "region": "N", "confirmed":[], "deaths":[]},
          {"state_name": "Rio Grande do Sul", "state_code": "RS", "region": "S", "confirmed":[], "deaths":[]},
          {"state_name": "Santa Catarina", "state_code": "SC", "region": "S", "confirmed":[], "deaths":[]},          
          {"state_name": "Sergipe", "state_code": "SE", "region": "NE", "confirmed":[], "deaths":[]},          
          {"state_name": "São Paulo", "state_code": "SP", "region": "SE", "confirmed":[], "deaths":[]},          
          {"state_name": "Tocantins", "state_code": "TO", "region": "N", "confirmed":[], "deaths":[]},                    
         ]

In [21]:
for item in output:
    code = item["state_code"]
    
    dates_conf = data_summary.loc[data_summary["state"] == code, "confirmed"].index
    confirmed = data_summary.loc[data_summary["state"] == code, "confirmed"].values
    dates_deaths = data_summary.loc[data_summary["state"] == code, "deaths"].index
    deaths = data_summary.loc[data_summary["state"] == code, "deaths"].values
        
    item["confirmed"] = [[date, int(value)] for date, value in zip(dates_conf, confirmed)]
    item["deaths"] = [[date, int(value)] for date, value in zip(dates_deaths, deaths)]

In [22]:
print(output)

[{'state_name': 'Acre', 'state_code': 'AC', 'region': 'N', 'confirmed': [['2020-03-17', 3], ['2020-03-18', 3], ['2020-03-19', 4], ['2020-03-20', 7], ['2020-03-21', 11], ['2020-03-22', 11], ['2020-03-23', 17], ['2020-03-24', 21], ['2020-03-25', 23], ['2020-03-26', 23], ['2020-03-27', 25], ['2020-03-28', 25], ['2020-03-29', 34], ['2020-03-30', 41], ['2020-03-31', 42], ['2020-04-01', 43], ['2020-04-02', 45], ['2020-04-03', 46], ['2020-04-04', 46], ['2020-04-05', 48], ['2020-04-06', 50], ['2020-04-07', 50], ['2020-04-08', 58], ['2020-04-09', 62], ['2020-04-10', 70], ['2020-04-11', 70]], 'deaths': [['2020-03-17', 0], ['2020-03-18', 0], ['2020-03-19', 0], ['2020-03-20', 0], ['2020-03-21', 0], ['2020-03-22', 0], ['2020-03-23', 0], ['2020-03-24', 0], ['2020-03-25', 0], ['2020-03-26', 0], ['2020-03-27', 0], ['2020-03-28', 0], ['2020-03-29', 0], ['2020-03-30', 0], ['2020-03-31', 0], ['2020-04-01', 0], ['2020-04-02', 0], ['2020-04-03', 0], ['2020-04-04', 0], ['2020-04-05', 0], ['2020-04-06', 1], ['2020-04-07', 2], ['2020-04-08', 2], ['2020-04-09', 2], ['2020-04-10', 2], ['2020-04-11', 2]]}, {'state_name': 'Alagoas', 'state_code': 'AL', 'region': 'NE', 'confirmed': [['2020-03-08', 1], ['2020-03-09', 1], ['2020-03-10', 1], ['2020-03-11', 1], ['2020-03-12', 1], ['2020-03-13', 1], ['2020-03-14', 1], ['2020-03-15', 1], ['2020-03-16', 1], ['2020-03-17', 1], ['2020-03-18', 1], ['2020-03-19', 4], ['2020-03-20', 6], ['2020-03-21', 7], ['2020-03-22', 7], ['2020-03-23', 8], ['2020-03-24', 10], ['2020-03-25', 11], ['2020-03-26', 11], ['2020-03-27', 12], ['2020-03-28', 14], ['2020-03-29', 17], ['2020-03-30', 17], ['2020-03-31', 18], ['2020-04-01', 18], ['2020-04-02', 18], ['2020-04-03', 23], ['2020-04-04', 23], ['2020-04-05', 28], ['2020-04-06', 31], ['2020-04-07', 34], ['2020-04-08', 37], ['2020-04-09', 37], ['2020-04-10', 45], ['2020-04-11', 45]], 'deaths': [['2020-03-08', 0], ['2020-03-09', 0], ['2020-03-10', 0], ['2020-03-11', 0], ['2020-03-12', 0], ['2020-03-13', 0], ['2020-03-14', 0], ['2020-03-15', 0], ['2020-03-16', 0], ['2020-03-17', 0], ['2020-03-18', 0], ['2020-03-19', 0], ['2020-03-20', 0], ['2020-03-21', 0], ['2020-03-22', 0], ['2020-03-23', 0], ['2020-03-24', 0], ['2020-03-25', 0], ['2020-03-26', 0], ['2020-03-27', 0], ['2020-03-28', 0], ['2020-03-29', 0], ['2020-03-30', 0], ['2020-03-31', 1], ['2020-04-01', 1], ['2020-04-02', 1], ['2020-04-03', 2], ['2020-04-04', 2], ['2020-04-05', 2], ['2020-04-06', 2], ['2020-04-07', 2], ['2020-04-08', 3], ['2020-04-09', 3], ['2020-04-10', 3], ['2020-04-11', 3]]}, {'state_name': 'Amazonas', 'state_code': 'AM', 'region': 'N', 'confirmed': [['2020-03-13', 1], ['2020-03-14', 1], ['2020-03-15', 1], ['2020-03-16', 1], ['2020-03-17', 1], ['2020-03-18', 2], ['2020-03-19', 3], ['2020-03-20', 7], ['2020-03-21', 18], ['2020-03-22', 26], ['2020-03-23', 32], ['2020-03-24', 47], ['2020-03-25', 54], ['2020-03-26', 67], ['2020-03-27', 81], ['2020-03-28', 111], ['2020-03-29', 140], ['2020-03-30', 151], ['2020-03-31', 175], ['2020-04-01', 200], ['2020-04-02', 229], ['2020-04-03', 260], ['2020-04-04', 311], ['2020-04-05', 417], ['2020-04-06', 532], ['2020-04-07', 636], ['2020-04-08', 804], ['2020-04-09', 899], ['2020-04-10', 981], ['2020-04-11', 981]], 'deaths': [['2020-03-13', 0], ['2020-03-14', 0], ['2020-03-15', 0], ['2020-03-16', 0], ['2020-03-17', 0], ['2020-03-18', 0], ['2020-03-19', 0], ['2020-03-20', 0], ['2020-03-21', 0], ['2020-03-22', 0], ['2020-03-23', 0], ['2020-03-24', 1], ['2020-03-25', 1], ['2020-03-26', 1], ['2020-03-27', 1], ['2020-03-28', 1], ['2020-03-29', 1], ['2020-03-30', 2], ['2020-03-31', 3], ['2020-04-01', 3], ['2020-04-02', 3], ['2020-04-03', 7], ['2020-04-04', 12], ['2020-04-05', 15], ['2020-04-06', 19], ['2020-04-07', 23], ['2020-04-08', 30], ['2020-04-09', 40], ['2020-04-10', 50], ['2020-04-11', 50]]}, {'state_name': 'Amapá', 'state_code': 'AP', 'region': 'N', 'confirmed': [['2020-03-20', 1], ['2020-03-21', 1], ['2020-03-22', 1], ['2020-03-23', 1], ['2020-03-24', 1], ['2020-03-25', 2], ['2020-03-26', 2], ['2020-03-27', 3], ['2020-03-28', 4], ['2020-03-29', 8], ['2020-03-30', 8], ['2020-03-31', 10], ['2020-04-01', 11], ['2020-04-02', 12], ['2020-04-03', 19], ['2020-04-04', 29], ['2020-04-05', 32], ['2020-04-06', 39], ['2020-04-07', 51], ['2020-04-08', 107], ['2020-04-09', 110], ['2020-04-10', 166], ['2020-04-11', 166]], 'deaths': [['2020-03-20', 0], ['2020-03-21', 0], ['2020-03-22', 0], ['2020-03-23', 0], ['2020-03-24', 0], ['2020-03-25', 0], ['2020-03-26', 0], ['2020-03-27', 0], ['2020-03-28', 0], ['2020-03-29', 0], ['2020-03-30', 0], ['2020-03-31', 0], ['2020-04-01', 0], ['2020-04-02', 0], ['2020-04-03', 0], ['2020-04-04', 1], ['2020-04-05', 1], ['2020-04-06', 2], ['2020-04-07', 2], ['2020-04-08', 2], ['2020-04-09', 2], ['2020-04-10', 2], ['2020-04-11', 2]]}, {'state_name': 'Bahia', 'state_code': 'BA', 'region': 'NE', 'confirmed': [['2020-03-06', 1], ['2020-03-07', 2], ['2020-03-08', 2], ['2020-03-09', 2], ['2020-03-10', 2], ['2020-03-11', 3], ['2020-03-12', 3], ['2020-03-13', 7], ['2020-03-14', 7], ['2020-03-15', 9], ['2020-03-16', 10], ['2020-03-17', 14], ['2020-03-18', 27], ['2020-03-19', 31], ['2020-03-20', 34], ['2020-03-21', 41], ['2020-03-22', 55], ['2020-03-23', 63], ['2020-03-24', 79], ['2020-03-25', 91], ['2020-03-26', 108], ['2020-03-27', 123], ['2020-03-28', 127], ['2020-03-29', 156], ['2020-03-30', 176], ['2020-03-31', 217], ['2020-04-01', 246], ['2020-04-02', 267], ['2020-04-03', 290], ['2020-04-04', 336], ['2020-04-05', 401], ['2020-04-06', 437], ['2020-04-07', 462], ['2020-04-08', 515], ['2020-04-09', 568], ['2020-04-10', 616], ['2020-04-11', 616]], 'deaths': [['2020-03-06', 0], ['2020-03-07', 0], ['2020-03-08', 0], ['2020-03-09', 0], ['2020-03-10', 0], ['2020-03-11', 0], ['2020-03-12', 0], ['2020-03-13', 0], ['2020-03-14', 0], ['2020-03-15', 0], ['2020-03-16', 0], ['2020-03-17', 0], ['2020-03-18', 0], ['2020-03-19', 0], ['2020-03-20', 0], ['2020-03-21', 0], ['2020-03-22', 0], ['2020-03-23', 0], ['2020-03-24', 0], ['2020-03-25', 0], ['2020-03-26', 0], ['2020-03-27', 0], ['2020-03-28', 0], ['2020-03-29', 1], ['2020-03-30', 2], ['2020-03-31', 2], ['2020-04-01', 2], ['2020-04-02', 3], ['2020-04-03', 6], ['2020-04-04', 7], ['2020-04-05', 9], ['2020-04-06', 10], ['2020-04-07', 14], ['2020-04-08', 18], ['2020-04-09', 19], ['2020-04-10', 19], ['2020-04-11', 19]]}, {'state_name': 'Ceará', 'state_code': 'CE', 'region': 'NE', 'confirmed': [['2020-03-16', 9], ['2020-03-17', 10], ['2020-03-18', 19], ['2020-03-19', 20], ['2020-03-20', 68], ['2020-03-21', 84], ['2020-03-22', 125], ['2020-03-23', 164], ['2020-03-24', 185], ['2020-03-25', 211], ['2020-03-26', 237], ['2020-03-27', 282], ['2020-03-28', 322], ['2020-03-29', 359], ['2020-03-30', 382], ['2020-03-31', 401], ['2020-04-01', 445], ['2020-04-02', 564], ['2020-04-03', 658], ['2020-04-04', 746], ['2020-04-05', 964], ['2020-04-06', 1047], ['2020-04-07', 1190], ['2020-04-08', 1190], ['2020-04-09', 1190], ['2020-04-10', 1190], ['2020-04-11', 1190]], 'deaths': [['2020-03-16', 0], ['2020-03-17', 0], ['2020-03-18', 0], ['2020-03-19', 0], ['2020-03-20', 0], ['2020-03-21', 0], ['2020-03-22', 0], ['2020-03-23', 0], ['2020-03-24', 0], ['2020-03-25', 0], ['2020-03-26', 3], ['2020-03-27', 3], ['2020-03-28', 4], ['2020-03-29', 5], ['2020-03-30', 5], ['2020-03-31', 7], ['2020-04-01', 9], ['2020-04-02', 0], ['2020-04-03', 22], ['2020-04-04', 23], ['2020-04-05', 35], ['2020-04-06', 36], ['2020-04-07', 40], ['2020-04-08', 40], ['2020-04-09', 40], ['2020-04-10', 40], ['2020-04-11', 40]]}, {'state_name': 'Distrito Federal', 'state_code': 'DF', 'region': 'CO', 'confirmed': [['2020-03-07', 1], ['2020-03-08', 1], ['2020-03-09', 1], ['2020-03-10', 1], ['2020-03-11', 2], ['2020-03-12', 2], ['2020-03-13', 2], ['2020-03-14', 8], ['2020-03-15', 14], ['2020-03-16', 19], ['2020-03-17', 19], ['2020-03-18', 34], ['2020-03-19', 42], ['2020-03-20', 87], ['2020-03-21', 108], ['2020-03-22', 117], ['2020-03-23', 138], ['2020-03-24', 161], ['2020-03-25', 191], ['2020-03-26', 201], ['2020-03-27', 241], ['2020-03-28', 260], ['2020-03-29', 298], ['2020-03-30', 312], ['2020-03-31', 333], ['2020-04-01', 370], ['2020-04-02', 400], ['2020-04-03', 419], ['2020-04-04', 456], ['2020-04-05', 468], ['2020-04-06', 485], ['2020-04-07', 503], ['2020-04-08', 509], ['2020-04-09', 527], ['2020-04-10', 527], ['2020-04-11', 527]], 'deaths': [['2020-03-07', 0], ['2020-03-08', 0], ['2020-03-09', 0], ['2020-03-10', 0], ['2020-03-11', 0], ['2020-03-12', 0], ['2020-03-13', 0], ['2020-03-14', 0], ['2020-03-15', 0], ['2020-03-16', 0], ['2020-03-17', 0], ['2020-03-18', 0], ['2020-03-19', 0], ['2020-03-20', 0], ['2020-03-21', 0], ['2020-03-22', 0], ['2020-03-23', 0], ['2020-03-24', 0], ['2020-03-25', 0], ['2020-03-26', 0], ['2020-03-27', 0], ['2020-03-28', 0], ['2020-03-29', 1], ['2020-03-30', 2], ['2020-03-31', 3], ['2020-04-01', 4], ['2020-04-02', 5], ['2020-04-03', 6], ['2020-04-04', 7], ['2020-04-05', 7], ['2020-04-06', 10], ['2020-04-07', 12], ['2020-04-08', 12], ['2020-04-09', 13], ['2020-04-10', 13], ['2020-04-11', 13]]}, {'state_name': 'Espírito Santo', 'state_code': 'ES', 'region': 'SE', 'confirmed': [['2020-03-19', 13], ['2020-03-20', 16], ['2020-03-21', 26], ['2020-03-22', 26], ['2020-03-23', 33], ['2020-03-24', 40], ['2020-03-25', 40], ['2020-03-26', 48], ['2020-03-27', 54], ['2020-03-28', 61], ['2020-03-29', 72], ['2020-03-30', 85], ['2020-03-31', 97], ['2020-04-01', 120], ['2020-04-02', 139], ['2020-04-03', 153], ['2020-04-04', 166], ['2020-04-05', 194], ['2020-04-06', 209], ['2020-04-07', 227], ['2020-04-08', 273], ['2020-04-09', 300], ['2020-04-10', 349], ['2020-04-11', 349]], 'deaths': [['2020-03-19', 0], ['2020-03-20', 0], ['2020-03-21', 0], ['2020-03-22', 0], ['2020-03-23', 0], ['2020-03-24', 0], ['2020-03-25', 0], ['2020-03-26', 0], ['2020-03-27', 0], ['2020-03-28', 0], ['2020-03-29', 0], ['2020-03-30', 0], ['2020-03-31', 0], ['2020-04-01', 0], ['2020-04-02', 2], ['2020-04-03', 5], ['2020-04-04', 6], ['2020-04-05', 6], ['2020-04-06', 6], ['2020-04-07', 6], ['2020-04-08', 6], ['2020-04-09', 7], ['2020-04-10', 8], ['2020-04-11', 8]]}, {'state_name': 'Goiás', 'state_code': 'GO', 'region': 'CO', 'confirmed': [['2020-03-12', 3], ['2020-03-13', 3], ['2020-03-14', 4], ['2020-03-15', 4], ['2020-03-16', 9], ['2020-03-17', 10], ['2020-03-18', 12], ['2020-03-19', 15], ['2020-03-20', 18], ['2020-03-21', 17], ['2020-03-22', 21], ['2020-03-23', 23], ['2020-03-24', 29], ['2020-03-25', 35], ['2020-03-26', 38], ['2020-03-27', 49], ['2020-03-28', 56], ['2020-03-29', 56], ['2020-03-30', 60], ['2020-03-31', 65], ['2020-04-01', 73], ['2020-04-02', 73], ['2020-04-03', 88], ['2020-04-04', 103], ['2020-04-05', 115], ['2020-04-06', 119], ['2020-04-07', 133], ['2020-04-08', 159], ['2020-04-09', 179], ['2020-04-10', 191], ['2020-04-11', 191]], 'deaths': [['2020-03-12', 0], ['2020-03-13', 0], ['2020-03-14', 0], ['2020-03-15', 0], ['2020-03-16', 0], ['2020-03-17', 0], ['2020-03-18', 0], ['2020-03-19', 0], ['2020-03-20', 0], ['2020-03-21', 0], ['2020-03-22', 0], ['2020-03-23', 0], ['2020-03-24', 0], ['2020-03-25', 0], ['2020-03-26', 1], ['2020-03-27', 1], ['2020-03-28', 1], ['2020-03-29', 1], ['2020-03-30', 1], ['2020-03-31', 1], ['2020-04-01', 1], ['2020-04-02', 1], ['2020-04-03', 2], ['2020-04-04', 2], ['2020-04-05', 3], ['2020-04-06', 5], ['2020-04-07', 5], ['2020-04-08', 7], ['2020-04-09', 7], ['2020-04-10', 8], ['2020-04-11', 8]]}, {'state_name': 'Maranhão', 'state_code': 'MA', 'region': 'NE', 'confirmed': [['2020-03-20', 1], ['2020-03-21', 2], ['2020-03-22', 2], ['2020-03-23', 8], ['2020-03-24', 8], ['2020-03-25', 8], ['2020-03-26', 10], ['2020-03-27', 13], ['2020-03-28', 15], ['2020-03-29', 21], ['2020-03-30', 30], ['2020-03-31', 51], ['2020-04-01', 70], ['2020-04-02', 80], ['2020-04-03', 87], ['2020-04-04', 95], ['2020-04-05', 132], ['2020-04-06', 171], ['2020-04-07', 229], ['2020-04-08', 272], ['2020-04-09', 293], ['2020-04-10', 344], ['2020-04-11', 344]], 'deaths': [['2020-03-20', 0], ['2020-03-21', 0], ['2020-03-22', 0], ['2020-03-23', 0], ['2020-03-24', 0], ['2020-03-25', 0], ['2020-03-26', 0], ['2020-03-27', 0], ['2020-03-28', 0], ['2020-03-29', 1], ['2020-03-30', 1], ['2020-03-31', 1], ['2020-04-01', 1], ['2020-04-02', 1], ['2020-04-03', 1], ['2020-04-04', 2], ['2020-04-05', 2], ['2020-04-06', 4], ['2020-04-07', 11], ['2020-04-08', 12], ['2020-04-09', 16], ['2020-04-10', 21], ['2020-04-11', 21]]}, {'state_name': 'Minas Gerais', 'state_code': 'MG', 'region': 'SE', 'confirmed': [['2020-03-08', 1], ['2020-03-09', 1], ['2020-03-10', 1], ['2020-03-11', 1], ['2020-03-12', 2], ['2020-03-13', 2], ['2020-03-14', 4], ['2020-03-15', 4], ['2020-03-16', 6], ['2020-03-17', 14], ['2020-03-18', 19], ['2020-03-19', 29], ['2020-03-20', 38], ['2020-03-21', 54], ['2020-03-22', 54], ['2020-03-23', 128], ['2020-03-24', 130], ['2020-03-25', 133], ['2020-03-26', 153], ['2020-03-27', 189], ['2020-03-28', 205], ['2020-03-29', 231], ['2020-03-30', 261], ['2020-03-31', 275], ['2020-04-01', 314], ['2020-04-02', 370], ['2020-04-03', 397], ['2020-04-04', 430], ['2020-04-05', 498], ['2020-04-06', 525], ['2020-04-07', 559], ['2020-04-08', 614], ['2020-04-09', 655], ['2020-04-10', 699], ['2020-04-11', 751]], 'deaths': [['2020-03-08', 0], ['2020-03-09', 0], ['2020-03-10', 0], ['2020-03-11', 0], ['2020-03-12', 0], ['2020-03-13', 0], ['2020-03-14', 0], ['2020-03-15', 0], ['2020-03-16', 0], ['2020-03-17', 0], ['2020-03-18', 0], ['2020-03-19', 0], ['2020-03-20', 0], ['2020-03-21', 0], ['2020-03-22', 0], ['2020-03-23', 0], ['2020-03-24', 0], ['2020-03-25', 0], ['2020-03-26', 0], ['2020-03-27', 0], ['2020-03-28', 0], ['2020-03-29', 0], ['2020-03-30', 1], ['2020-03-31', 2], ['2020-04-01', 3], ['2020-04-02', 4], ['2020-04-03', 6], ['2020-04-04', 6], ['2020-04-05', 6], ['2020-04-06', 9], ['2020-04-07', 11], ['2020-04-08', 14], ['2020-04-09', 15], ['2020-04-10', 17], ['2020-04-11', 17]]}, {'state_name': 'Mato Grosso do Sul', 'state_code': 'MS', 'region': 'CO', 'confirmed': [['2020-03-14', 2], ['2020-03-15', 2], ['2020-03-16', 4], ['2020-03-17', 6], ['2020-03-18', 7], ['2020-03-19', 9], ['2020-03-20', 12], ['2020-03-21', 16], ['2020-03-22', 21], ['2020-03-23', 21], ['2020-03-24', 24], ['2020-03-25', 24], ['2020-03-26', 25], ['2020-03-27', 28], ['2020-03-28', 31], ['2020-03-29', 36], ['2020-03-30', 44], ['2020-03-31', 48], ['2020-04-01', 51], ['2020-04-02', 53], ['2020-04-03', 60], ['2020-04-04', 62], ['2020-04-05', 65], ['2020-04-06', 66], ['2020-04-07', 80], ['2020-04-08', 85], ['2020-04-09', 89], ['2020-04-10', 97], ['2020-04-11', 97]], 'deaths': [['2020-03-14', 0], ['2020-03-15', 0], ['2020-03-16', 0], ['2020-03-17', 0], ['2020-03-18', 0], ['2020-03-19', 0], ['2020-03-20', 0], ['2020-03-21', 0], ['2020-03-22', 0], ['2020-03-23', 0], ['2020-03-24', 0], ['2020-03-25', 0], ['2020-03-26', 0], ['2020-03-27', 0], ['2020-03-28', 0], ['2020-03-29', 0], ['2020-03-30', 0], ['2020-03-31', 1], ['2020-04-01', 1], ['2020-04-02', 1], ['2020-04-03', 1], ['2020-04-04', 1], ['2020-04-05', 1], ['2020-04-06', 1], ['2020-04-07', 2], ['2020-04-08', 2], ['2020-04-09', 2], ['2020-04-10', 2], ['2020-04-11', 2]]}, {'state_name': 'Mato Grosso', 'state_code': 'MT', 'region': 'CO', 'confirmed': [['2020-03-20', 1], ['2020-03-21', 1], ['2020-03-22', 1], ['2020-03-23', 6], ['2020-03-24', 7], ['2020-03-25', 9], ['2020-03-26', 11], ['2020-03-27', 11], ['2020-03-28', 11], ['2020-03-29', 11], ['2020-03-30', 18], ['2020-03-31', 25], ['2020-04-01', 28], ['2020-04-02', 41], ['2020-04-03', 44], ['2020-04-04', 60], ['2020-04-05', 60], ['2020-04-06', 76], ['2020-04-07', 78], ['2020-04-08', 90], ['2020-04-09', 108], ['2020-04-10', 112], ['2020-04-11', 112]], 'deaths': [['2020-03-20', 0], ['2020-03-21', 0], ['2020-03-22', 0], ['2020-03-23', 0], ['2020-03-24', 0], ['2020-03-25', 0], ['2020-03-26', 0], ['2020-03-27', 0], ['2020-03-28', 0], ['2020-03-29', 0], ['2020-03-30', 0], ['2020-03-31', 0], ['2020-04-01', 0], ['2020-04-02', 0], ['2020-04-03', 1], ['2020-04-04', 1], ['2020-04-05', 1], ['2020-04-06', 1], ['2020-04-07', 1], ['2020-04-08', 1], ['2020-04-09', 2], ['2020-04-10', 2], ['2020-04-11', 2]]}, {'state_name': 'Pará', 'state_code': 'PA', 'region': 'N', 'confirmed': [['2020-03-18', 1], ['2020-03-19', 1], ['2020-03-20', 2], ['2020-03-21', 2], ['2020-03-22', 4], ['2020-03-23', 5], ['2020-03-24', 5], ['2020-03-25', 7], ['2020-03-26', 13], ['2020-03-27', 16], ['2020-03-28', 18], ['2020-03-29', 20], ['2020-03-30', 26], ['2020-03-31', 34], ['2020-04-01', 41], ['2020-04-02', 49], ['2020-04-03', 75], ['2020-04-04', 82], ['2020-04-05', 86], ['2020-04-06', 123], ['2020-04-07', 154], ['2020-04-08', 165], ['2020-04-09', 169], ['2020-04-10', 217], ['2020-04-11', 217]], 'deaths': [['2020-03-18', 0], ['2020-03-19', 0], ['2020-03-20', 0], ['2020-03-21', 0], ['2020-03-22', 0], ['2020-03-23', 0], ['2020-03-24', 0], ['2020-03-25', 0], ['2020-03-26', 0], ['2020-03-27', 0], ['2020-03-28', 0], ['2020-03-29', 0], ['2020-03-30', 0], ['2020-03-31', 0], ['2020-04-01', 1], ['2020-04-02', 1], ['2020-04-03', 1], ['2020-04-04', 1], ['2020-04-05', 1], ['2020-04-06', 5], ['2020-04-07', 5], ['2020-04-08', 6], ['2020-04-09', 7], ['2020-04-10', 9], ['2020-04-11', 9]]}, {'state_name': 'Paraíba', 'state_code': 'PB', 'region': 'NE', 'confirmed': [['2020-03-18', 1], ['2020-03-19', 1], ['2020-03-20', 1], ['2020-03-21', 1], ['2020-03-22', 1], ['2020-03-23', 2], ['2020-03-24', 3], ['2020-03-25', 5], ['2020-03-26', 6], ['2020-03-27', 10], ['2020-03-28', 14], ['2020-03-29', 14], ['2020-03-30', 17], ['2020-03-31', 18], ['2020-04-01', 21], ['2020-04-02', 29], ['2020-04-03', 32], ['2020-04-04', 34], ['2020-04-05', 35], ['2020-04-06', 36], ['2020-04-07', 41], ['2020-04-08', 55], ['2020-04-09', 79], ['2020-04-10', 85], ['2020-04-11', 85]], 'deaths': [['2020-03-18', 0], ['2020-03-19', 0], ['2020-03-20', 0], ['2020-03-21', 0], ['2020-03-22', 0], ['2020-03-23', 0], ['2020-03-24', 0], ['2020-03-25', 0], ['2020-03-26', 0], ['2020-03-27', 0], ['2020-03-28', 0], ['2020-03-29', 0], ['2020-03-30', 0], ['2020-03-31', 1], ['2020-04-01', 1], ['2020-04-02', 1], ['2020-04-03', 1], ['2020-04-04', 3], ['2020-04-05', 4], ['2020-04-06', 4], ['2020-04-07', 4], ['2020-04-08', 7], ['2020-04-09', 11], ['2020-04-10', 11], ['2020-04-11', 11]]}, {'state_name': 'Pernambuco', 'state_code': 'PE', 'region': 'NE', 'confirmed': [['2020-03-12', 2], ['2020-03-13', 2], ['2020-03-14', 7], ['2020-03-15', 8], ['2020-03-16', 8], ['2020-03-17', 18], ['2020-03-18', 19], ['2020-03-19', 19], ['2020-03-20', 19], ['2020-03-21', 33], ['2020-03-22', 37], ['2020-03-23', 42], ['2020-03-24', 42], ['2020-03-25', 46], ['2020-03-26', 48], ['2020-03-27', 57], ['2020-03-28', 68], ['2020-03-29', 73], ['2020-03-30', 77], ['2020-03-31', 87], ['2020-04-01', 95], ['2020-04-02', 106], ['2020-04-03', 136], ['2020-04-04', 176], ['2020-04-05', 201], ['2020-04-06', 223], ['2020-04-07', 352], ['2020-04-08', 401], ['2020-04-09', 555], ['2020-04-10', 684], ['2020-04-11', 684]], 'deaths': [['2020-03-12', 0], ['2020-03-13', 0], ['2020-03-14', 0], ['2020-03-15', 0], ['2020-03-16', 0], ['2020-03-17', 0], ['2020-03-18', 0], ['2020-03-19', 0], ['2020-03-20', 0], ['2020-03-21', 0], ['2020-03-22', 0], ['2020-03-23', 0], ['2020-03-24', 0], ['2020-03-25', 1], ['2020-03-26', 3], ['2020-03-27', 4], ['2020-03-28', 5], ['2020-03-29', 5], ['2020-03-30', 6], ['2020-03-31', 6], ['2020-04-01', 8], ['2020-04-02', 9], ['2020-04-03', 10], ['2020-04-04', 14], ['2020-04-05', 21], ['2020-04-06', 30], ['2020-04-07', 34], ['2020-04-08', 46], ['2020-04-09', 56], ['2020-04-10', 65], ['2020-04-11', 65]]}, {'state_name': 'Piauí', 'state_code': 'PI', 'region': 'NE', 'confirmed': [['2020-03-19', 3], ['2020-03-20', 4], ['2020-03-21', 4], ['2020-03-22', 6], ['2020-03-23', 6], ['2020-03-24', 8], ['2020-03-25', 9], ['2020-03-26', 9], ['2020-03-27', 10], ['2020-03-28', 11], ['2020-03-29', 11], ['2020-03-30', 18], ['2020-03-31', 18], ['2020-04-01', 19], ['2020-04-02', 19], ['2020-04-03', 22], ['2020-04-04', 24], ['2020-04-05', 24], ['2020-04-06', 26], ['2020-04-07', 31], ['2020-04-08', 38], ['2020-04-09', 40], [

In [23]:
with open('state_summary.json', 'w') as f:
    json.dump(output, f)